### ISSUE TITLE
Prediction example

### ISSUE THREAD

**Issue by mg64ve** [bquast/rnn#17]
Hi, your code looks good. Thanks for sharing!
I am just doing the first steps with few experience with RNN.
I have just run your finance example.
Correct me if I am wrong, if I run the example with 300 epochs and 10 hidden nodes, the predicted curve that I observe always follow the real one. The number of day in advance is 1.
In this case I expect to see predicted curve that is 1 day shifted in advance with the respect of the real one. What I see is the the predicted curve is 1 day postponed.
Is there anything the influences this result?
Thanks.
Best regards.

**Comment by bquast** [comment]
Hi, the issues section is more for problem with the code, rather than problems with how to use it. Please post this on StackOverflow.com you can email me the link.

**Comment by SatoshiReport** [comment]
For those looking, it can be found here: http://stackoverflow.com/questions/40452523/predicting-multivariate-time-series-with-rnn

**Comment by mg64ve** [comment]
Dear Bastiaan,

thanks for your reply.
I have just added one comment.
Could you please check it?
I wonder to know if I am trying to use your library in the correct way.

Thanks.
Best regards.

2016-11-19 5:38 GMT+01:00 SatoshiReport <notifications@github.com>:

**Comment by mg64ve** [comment]
Sorry, if my question is silly or does not make sense you should tell me.

Thanks.
Regards.

2016-11-26 18:17 GMT+01:00 Marco Marco <mg64ve@gmail.com>:
