### ISSUE TITLE
int2bin doesn't work on 64bit platform

### ISSUE THREAD

**Issue by wliangaz** [bquast/rnn#24]
As titled. I'm running in Rstudio on windows 10 env., and I went through vignette example, the test part gave me trouble. A test example yielded result like this:

> bin2int(int2bin(3))
[1] 50331648

**Comment by bquast** [comment]
This code is no longer supported.

The examples define these functions.

This is not a help forum

**Comment by wliangaz** [comment]
i clicked 'report issue' link to get here, remove it then. oic, not a help forum, yet i didn't ask help for your glorious package...never mind.
