### ISSUE TITLE
Problem with negative number

### ISSUE THREAD

**Issue by vinhqdang** [bquast/rnn#7]
Hello

I noticed that, if I do ``int2bin`` and ``bin2int`` consequently on negative number, I will get a positive number afterwards.

While the mechanism of converting is understandable, I think it would raise confusion, especially the function name ``int2bin`` suggests that it should work with ``int``, not ``unsigned int`` only.

**Comment by bquast** [comment]
Thanks, that is a good point. As I mentioned before, these functions were included for the PoW bit-by-bit summation. They're no longer part of the core functionality and will eventually be removed.

**Comment by vinhqdang** [comment]
Thanks a lot,

Btw, could RNN works with factor variables? For instance, X1 and X2 are not numeric but factor variables?
—
Best Regards

Vinh

**Comment by bquast** [comment]
It would be great if you could ask that question on www.stackoverflow.com and paste the link here, that way others can also benefit from the answer.

**Comment by vinhqdang** [comment]
Oops, sorry, I will do that.
—
Best Regards

Vinh

**Comment by vinhqdang** [comment]
Hi

The question is there

http://stackoverflow.com/questions/37742290/using-rnn-in-r-with-factor-variable

**Comment by bquast** [comment]
Great, it will try to answer it on Sunday I am travelling now.

**Comment by vinhqdang** [comment]
Thanks there

**Comment by bquast** [comment]
Hi Vinh,

I just had a look at your question, but it seems to have been closed, it looks like this is because it didn't include a sort of working in progress.

You could edit the question to create some sample data and then run it and say: I get this error... does that make sense?

**Comment by vinhqdang** [comment]
Oops, I did not get notifications about your answer. I posted a new one here:

http://stackoverflow.com/questions/38334076/using-rnn-in-r-with-factorial-input-variables

**Comment by vinhqdang** [comment]
Hi,

Thanks for your answer on stackoverflow.

Could you take a look at https://github.com/bquast/rnn/issues/6 as well?
